const payrollStruct = {
    numero: 'N°',
    tipo_empleado: 'Tipo de empleado',
    tipo_documento: 'Tipo de documento',
    cedula: 'Cedula',
    primer_nombre: '1mer nombre',
    segundo_nombre: '2do nombre',
    primer_apellido: '1mer apellido',
    segundo_apellido: '2do apellido',
    subtipo_empleado: 'Subtipo empleado',
    fecha_ingreso: 'Fecha de ingreso',
    Dias_en_la_empresa: 'Dias empresa',
    tipo_contrato: 'Tipo de contrato',
    direccion: 'Direccion',
    municipio: 'Municipio',
    correo: 'Correo',
    tipo_salario: 'Tipo Salario',
    pensionado: 'Pensionado',
    horas_mes: 'Horas Mes',
    sueldo_contrato: 'Sueldo Contrato',
    dias: 'dias',
    ieg: 'ieg',
    lm: 'lm',
    lp: 'lp',
    vac: 'vac',
    hed: 'hed',
    hen: 'hen',
    rn: 'rn',
    rd: 'rd',
    hedd: 'hedd',
    hedn: 'hedn',
    rdn: 'rdn',
    sueldo_basico: 'sueldo_basico',
    incapacidad_general: 'incapacidad_general',
    incapacidad_tipo: 'incapacidad_tipo',
    incapacidad_fecha_inicial: 'incapacidad_fecha_inicial',
    incapacidad_fecha_final: 'incapacidad_fecha_final',
    licencia_maternidad: 'licencia_maternidad',
    licencia_maternidad_fecha_inicial: 'licencia_maternidad_fecha_inicial',
    licencia_maternidad_fecha_final: 'licencia_maternidad_fecha_final',
    auxilio_transporte: 'auxilio_transporte',
    horas_extras_diurnas_125: 'horas_extras_diurnas_125',
    horas_extras_nocturnas_175: 'horas_extras_nocturnas_175',
    recargo_nocturno_35: 'recargo_nocturno_35',
    recargo_dominical_festivo_180: 'recargo_dominical_festivo_180',
    horas_extras_diurna_dominical_205: 'horas_extras_diurna_dominical_205',
    horas_extras_nocturna_dominical_255: 'horas_extras_nocturna_dominical_255',
    recargo_dominical_festivo_nocturno_215: 'recargo_dominical_festivo_nocturno_215',
    otros_devengos_salariales: 'otros_devengos_salariales',
    otros_devengos_no_salariales: 'otros_devengos_no_salariales',
    vacaciones_disfrutadas: 'vacaciones_disfrutadas',
    vacaciones_salida: 'vacaciones_salida',
    vacaciones_ingreso: 'vacaciones_ingreso',
    vacaciones_dias: 'vacaciones_dias',
    vacaciones_compensadas: 'vacaciones_compensadas',
    vacaciones_compensadas_dias: 'vacaciones_compensadas_dias',
    dotacion: 'dotacion',
    prima_servicios: 'prima_servicios',
    cesantia: 'cesantia',
    cesantias_depositadas_fondo: 'cesantias_depositadas_fondo',
    intereses_cesantias: 'intereses_cesantias',
    licencia_paternidad: 'licencia_paternidad',
    licencia_paternidad_fecha_inicial: 'licencia_paternidad_fecha_inicial',
    licencia_paternidad_fecha_final: 'licencia_paternidad_fecha_final',
    auxilio_salarial: 'auxilio_salarial',
    auxilio_no_salarial: 'auxilio_no_salarial',
    total_devengado: 'total_devengado',
    aportes_salud: 'aportes_salud',
    aportes_pension: 'aportes_pension',
    fsp: 'fsp',
    retencion_fuente: 'retencion_fuente',
    otras_deducciones: 'otras_deducciones',
    total_deducciones: 'total_deducciones',
    neto_pagar: 'neto_pagar',
    vacio: 'vacio', // columna vacía
    ibc: 'ibc',
    arl_porcentaje: 'arl_porcentaje',
    salud_empresa: 'salud_empresa',
    pension_empresa: 'pension_empresa',
    arl: 'arl',
    icbf: 'icbf',
    sena: 'sena',
    ccf: 'ccf',
    prima_servicios_total: 'prima_servicios_total',
    cesantia_total: 'cesantia_total',
    intereses_cesantias_total: 'intereses_cesantias_total',
    vacaciones: 'vacaciones',
    banco: 'banco',
    tipo_cuenta: 'tipo_cuenta',
    numero_cuenta: 'numero_cuenta',
    metodo_pago: 'metodo_pago',
    fecha_pago1: 'fecha_pago1',
    fecha_pago2: 'fecha_pago2'
}

module.exports = { payrollStruct };