const payrollStruct = {
    numero: 'N°',
    tipo_empleado: 'Tipo de empleado',
    tipo_documento: 'Tipo de documento',
    cedula: 'Cedula',
    primer_nombre: '1mer nombre',
    segundo_nombre: '2do nombre',
    primer_apellido: '1mer apellido',
    segundo_apellido: '2do apellido',
    subtipo_empleado: 'Subtipo empleado',
    fecha_ingreso: 'Fecha de ingreso',
    Dias_en_la_empresa: 'Dias empresa',
    tipo_contrato: 'Tipo de contrato',
    direccion: 'Direccion',
    municipio: 'Municipio',
    correo: 'Correo',
    tipo_salario: 'Tipo Salario',
    horas_mes: 'Horas Mes',
    sueldo_contrato: 'Sueldo Contrato',
    dias: 'dias',
    ieg: 'ieg',
    lm: 'lm',
    hed: 'hed',
    hen: 'hen',
    rn: 'rn',
    rd: 'rd',
    sueldo_basico: 'sueldo_basico',
    incapacidad_general: 'incapacidad_general',
    licencia_maternidad: 'licencia_maternidad',
    auxilio_transporte: 'auxilio_transporte',
    horas_extras_diurnas_125: 'horas_extras_diurnas_125',
    horas_extras_nocturnas_175: 'horas_extras_nocturnas_175',
    recargo_nocturno_35: 'recargo_nocturno_35',
    recargo_dominical_festivo_180: 'recargo_dominical_festivo_180',
    otros_devengos_salariales: 'otros_devengos_salariales',
    otros_devengos_no_salariales: 'otros_devengos_no_salariales',
    total_devengado: 'total_devengado',
    aportes_salud: 'aportes_salud',
    aportes_pension: 'aportes_pension',
    fsp: 'fsp',
    retencion_fuente: 'retencion_fuente',
    otras_deducciones: 'otras_deducciones',
    total_deducciones: 'total_deducciones',
    neto_pagar: 'neto_pagar',
    vacio: 'vacio', // columna vacía
    ibc: 'ibc',
    arl_porcentaje: 'arl_porcentaje',
    salud_empresa: 'salud_empresa',
    pension_empresa: 'pension_empresa',
    arl: 'arl',
    icbf: 'icbf',
    sena: 'sena',
    ccf: 'ccf',
    prima_servicios: 'prima_servicios',
    cesantia: 'cesantia',
    intereses_cesantias: 'intereses_cesantias',
    vacaciones: 'vacaciones',
    banco: 'banco',
    tipo_cuenta: 'tipo_cuenta',
    numero_cuenta: 'numero_cuenta',
    metodo_pago: 'metodo_pago',
    fecha_pago1: 'fecha_pago1',
    fecha_pago2: 'fecha_pago2',
}

module.exports = { payrollStruct };